name: Leaves Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      id: github
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: SHA of the commit
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "::set-output name=short_sha::$calculatedSha"
        
    - name: Build and push docker image
      env:
        DH_USERNAME: ${{ secrets.DH_USERNAME }}
        IMAGE_TAG: ${{ steps.vars.outputs.short_sha }}
      run: |
        docker login -u $DH_USERNAME -p ${{ secrets.DH_PASSWORD }}
        docker build -f Dockerfile -t $DH_USERNAME/work360-services-leaves:$IMAGE_TAG -t $DH_USERNAME/work360-services-leaves:latest .
        docker push $DH_USERNAME/work360-services-leaves --all-tags
